import './style.css'
import type { GpReport } from './shared/gpReport'
import { getReport, isReplay, pageUrl, modeBanner } from './demoClient'
import { replayLabel } from './shared/replay'
import type { UnifiedCheckin } from './shared/checkin'
type Report = GpReport
const app = document.querySelector<HTMLDivElement>('#app')!
const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
const date = (value: string) => new Date(value.slice(0,10)+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})
const medication: Record<string,string> = {reported_taken:'Reported taken',reported_missed:'Reported missed',reported_not_yet_taken:'Not yet taken',uncertain:'Patient unsure'}
function checkinCard(record: UnifiedCheckin, outside: boolean) {
  const observations = record.observations.filter(o=>!(o.category==='emotional_state'&&o.value.missing))
  return `<article class="patient-record"><div class="record-heading"><strong>${esc(new Date(record.timestamp).toLocaleString('en-GB'))}</strong><span class="status-pill">${record.confirmationStatus==='confirmed'?'Confirmed':'Unconfirmed interpretation'}</span></div>${record.provenance?`<p class="replay-provenance">${esc(replayLabel(record.provenance.origin))}${record.provenance.model?` · ${esc(record.provenance.model)}`:''}</p>`:''}${outside?'<p class="outside-note">Captured after the September report period · shown separately from period calculations.</p>':''}<p>${record.extractionStatus==='failed'?'Extraction unavailable · transcript retained':observations.length?observations.map(o=>{let label=String(o.value.label??o.value.state??o.value.topic??o.code);if(o.category==='medication_adherence')label=medication[String(o.value.state)]??label; if(o.category==='symptom')label+=` (${o.value.status})`;return `<span class="observation-chip">${esc(label)}</span>`}).join(' '):'No observations extracted'}</p>${record.requiresHumanReview?'<p class="review-tag">◇ Review suggested · clarification only</p>':''}<details><summary>Transcript & evidence</summary><blockquote>${esc(record.transcript)}</blockquote><ul>${observations.filter(o=>o.evidence).map(o=>`<li>${esc(o.category)}: “${esc(o.evidence)}”</li>`).join('')}</ul><p>Source: ${esc(record.inputSource)} · Record ID: ${esc(record.id)}</p><details><summary>Unified record JSON</summary><pre>${esc(JSON.stringify(record,null,2))}</pre></details></details></article>`
}
function bpChart(report: Report) {
  const readings=[...report.bloodPressure].sort((a,b)=>a.timestamp.localeCompare(b.timestamp))
  const min=Math.floor((Math.min(...readings.map(r=>r.diastolic))-10)/10)*10
  const max=Math.ceil((Math.max(...readings.map(r=>r.systolic))+10)/10)*10
  const x=(i:number)=>55+i*790/(readings.length-1)
  const y=(n:number)=>260-(n-min)/(max-min)*210
  const line=(key:'systolic'|'diastolic')=>readings.map((r,i)=>`${i?'L':'M'} ${x(i)} ${y(r[key])}`).join(' ')
  const bands=report.missedClusters.map(cluster=>{const first=readings.findIndex(r=>r.timestamp.startsWith(cluster.from));const last=readings.findIndex(r=>r.timestamp.startsWith(cluster.to));return first>=0&&last>=0?`<rect x="${x(first)-10}" y="35" width="${x(last)-x(first)+20}" height="225" fill="#f6e1c5"/>`:''}).join('')
  const ticks=Array.from({length:Math.floor((max-min)/20)+1},(_,i)=>min+i*20).map(n=>`<line x1="55" x2="845" y1="${y(n)}" y2="${y(n)}" stroke="#e8e8e3"/><text x="40" y="${y(n)+4}" text-anchor="end">${n}</text>`).join('')
  return `<svg class="bp-chart" viewBox="0 0 890 310" role="img" aria-labelledby="chartTitle chartDesc"><title id="chartTitle">30-day systolic and diastolic blood pressure</title><desc id="chartDesc">Synthetic readings for September. Both series rise beginning September 19. Shading marks consecutive missed dispensing on September 18–20. Exact readings are available in the table below.</desc>${bands}${ticks}<path d="${line('systolic')}" fill="none" stroke="#25796d" stroke-width="3"/><path d="${line('diastolic')}" fill="none" stroke="#8872b1" stroke-width="3" stroke-dasharray="6 4"/>${readings.map((r,i)=>`<circle cx="${x(i)}" cy="${y(r.systolic)}" r="3" fill="#25796d"><title>${esc(date(r.timestamp))}: ${r.systolic}/${r.diastolic} mmHg</title></circle>`).join('')}${[0,6,13,20,29].map(i=>`<text x="${x(i)}" y="287" text-anchor="middle">${i+1} Sep</text>`).join('')}<text x="55" y="22">mmHg</text></svg>`
}
function render(report: Report) {
  const last=report.wearable[report.wearable.length-1]
  const inPeriod=report.checkins.filter(c=>c.timestamp.slice(0,10)>=report.metrics.period.from&&c.timestamp.slice(0,10)<=report.metrics.period.to)
  const outside=report.checkins.filter(c=>c.timestamp.slice(0,10)<report.metrics.period.from||c.timestamp.slice(0,10)>report.metrics.period.to)
  app.innerHTML=`<div class="gp-shell"><header class="demo-header"><a class="brand" href="${pageUrl('')}">Pulse<span>Note</span><small>SCHOOL MVP · SYNTHETIC DATA</small></a><div class="header-actions"><a href="${pageUrl('')}">← Smartwatch</a><button id="refreshReport">Refresh</button><button id="printReport">Print</button></div></header>${modeBanner()}<div class="report-heading"><div><p class="eyebrow">GP / PRE-CONSULTATION OVERVIEW</p><h1>${esc(report.patientName)}’s month at a glance</h1><p>${date(report.metrics.period.from)} — ${date(report.metrics.period.to)} · ${report.metrics.period.days} days</p></div><span class="status-pill">One fictional patient</span></div><p class="synthetic-banner">Synthetic school demonstration. No diagnosis, triage or treatment advice. Dispensing does not verify ingestion.</p>
  <div class="metric-row"><section class="adherence-card"><p>Dispensing adherence</p><strong>${report.dispensingAdherence??'—'}<small>%</small></strong><span>${report.metrics.dispenser.dispensed} of ${report.metrics.dispenser.scheduled} scheduled events dispensed</span><details><summary>Why this percentage?</summary><p>${report.metrics.dispenser.dispensed} ÷ ${report.metrics.dispenser.scheduled} × 100 = ${report.dispensingAdherence}%. Calculated from dispenser records only; smartwatch acknowledgements and patient statements are excluded.</p></details></section><section class="metric-card"><p>Average blood pressure</p><strong>${report.metrics.bloodPressure.averageSystolic}/${report.metrics.bloodPressure.averageDiastolic}</strong><span>mmHg · ${report.metrics.bloodPressure.readings} synthetic monitor readings</span></section><section class="metric-card"><p>Missed dispensing</p><strong>${report.metrics.dispenser.missed}<small> / ${report.metrics.dispenser.scheduled}</small></strong><span>${report.missedClusters.length} consecutive missed-event cluster</span></section></div>
  <section class="dashboard-card"><div class="card-heading"><div><p class="eyebrow">OBJECTIVE SYNTHETIC RECORDS</p><h2>Blood-pressure trend</h2></div><div class="chart-legend"><span>● Systolic</span><span>┄ Diastolic</span><span>▧ Missed cluster</span></div></div>${bpChart(report)}<details><summary>View all 30 underlying records</summary><div class="records-table"><table><thead><tr><th>Date</th><th>Systolic</th><th>Diastolic</th><th>20:00 dispensing</th></tr></thead><tbody>${report.daily.map(day=>`<tr class="${day.dispenser==='missed'?'missed-row':''}"><td>${esc(day.date)}</td><td>${day.systolic}</td><td>${day.diastolic}</td><td>${esc(day.dispenser)}</td></tr>`).join('')}</tbody></table></div></details></section>
  ${report.missedClusters.map(cluster=>`<section class="pattern-card"><p class="eyebrow">PATTERN DETECTED</p><h2>${cluster.count} consecutive evening dispensing events missed</h2><p>${date(cluster.from)} — ${date(cluster.to)}. ${cluster.higherBpDuringCluster?'Higher BP readings were recorded during the same period.':'The linked BP records are shown below.'} This describes timing; it does not establish causation.</p><details><summary>Why? See the actual records</summary><p>Detector: at least three missed events on consecutive calendar days. BP comparison uses the seven preceding days versus the cluster days; the demo marks a rise of at least ${report.config.risingTrendMmHg} mmHg in average systolic BP.</p><p>Average systolic: ${cluster.beforeAverageSystolic} mmHg before, ${cluster.duringAverageSystolic} mmHg during. The chart shows the change beginning around day 19.</p><div class="records-table"><table><thead><tr><th>Scheduled evening event</th><th>Status</th><th>Medication</th><th>Record ID</th></tr></thead><tbody>${cluster.events.map(event=>`<tr><td>${esc(new Date(event.scheduledAt).toLocaleString('en-GB',{timeZone:'Europe/Amsterdam'}))} (Amsterdam)</td><td>${esc(event.status)}</td><td>${esc(event.medication)}</td><td>${esc('id' in event?event.id:'—')}</td></tr>`).join('')}</tbody></table><table><thead><tr><th>BP date</th><th>BP (mmHg)</th><th>Comparison window</th></tr></thead><tbody>${[...cluster.beforeReadings,...cluster.duringReadings].map(r=>`<tr><td>${esc(r.timestamp.slice(0,10))}</td><td>${r.systolic}/${r.diastolic}</td><td>${r.timestamp.slice(0,10)<cluster.from?'Before':'During'}</td></tr>`).join('')}</tbody></table></div></details></section>`).join('')}
  <div class="context-grid"><section class="dashboard-card"><p class="eyebrow">WEARABLE CONTEXT · SYNTHETIC</p><h2>Daily context</h2><p>Same snapshot as the smartwatch · ${date(last.date)}</p><div class="wearable-grid"><div><strong>${last.restingHeartRate}</strong><span>Resting HR · bpm</span></div><div><strong>${Math.floor(last.sleepMinutes/60)}h ${last.sleepMinutes%60}m</strong><span>Sleep</span></div><div><strong>${last.steps.toLocaleString()}</strong><span>Steps</span></div><div><strong>${last.activityMinutes}m</strong><span>Activity</span></div></div><details><summary>30-day wearable records</summary><div class="records-table"><table><thead><tr><th>Date</th><th>HR</th><th>Sleep (min)</th><th>Steps</th><th>Activity (min)</th></tr></thead><tbody>${report.wearable.map(d=>`<tr><td>${d.date}</td><td>${d.restingHeartRate}</td><td>${d.sleepMinutes}</td><td>${d.steps}</td><td>${d.activityMinutes}</td></tr>`).join('')}</tbody></table></div></details></section><section class="dashboard-card"><p class="eyebrow">PATIENT-REPORTED · SEPARATE SOURCE</p><h2>Voice check-ins</h2><p>AI interpretations of patient speech are unconfirmed unless explicitly reviewed. They do not change dispensing adherence.</p>${inPeriod.map(c=>checkinCard(c,false)).join('')||'<p>No check-ins in this reporting period.</p>'}${outside.length?`<h3>Captured outside the report period</h3>${outside.map(c=>checkinCard(c,true)).join('')}`:''}</section></div><footer class="demo-footer">Generated ${esc(new Date(report.generatedAt).toLocaleString())} · ${isReplay?'Replay records stay in this browser tab until Reset or the tab is closed.':'In-memory live records reset when the server restarts.'}</footer></div>`
  document.getElementById('refreshReport')!.addEventListener('click',()=>void load())
  document.getElementById('printReport')!.addEventListener('click',()=>window.print())
}
async function load() {
  try { render(await getReport()) }
  catch(error){app.innerHTML=`<div class="gp-shell"><h1>Overview unavailable</h1><p role="alert">${esc(error instanceof Error?error.message:error)}</p><button id="retryLoad">Try again</button> <a href="${pageUrl('')}">Back to smartwatch</a></div>`;document.getElementById('retryLoad')!.addEventListener('click',()=>void load())}
}
app.innerHTML='<div class="gp-shell"><p role="status">Loading the shared records…</p></div>'
window.addEventListener('focus',()=>void load())
void load()
